import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, Gauge, Lock, Save, ShieldCheck, ThumbsDown, ThumbsUp, X } from "lucide-react";
import { getJson, sendJson } from "../api";
import { Badge, Button, EmptyState, ErrorState, formatDate, JsonDetails, LoadingState, PageHeader } from "../components/ui";

export function InboxPage({ privacy, resources }: { privacy: any; resources: any }) {
  const client = useQueryClient();
  const [apps, setApps] = useState("");
  const [domains, setDomains] = useState("");
  useEffect(() => { setApps((privacy?.capture?.excluded_apps || []).join(", ")); setDomains((privacy?.capture?.excluded_domains || []).join(", ")); }, [privacy?.capture?.excluded_apps, privacy?.capture?.excluded_domains]);
  const inbox = useQuery({ queryKey: ["proactive-inbox"], queryFn: async () => {
    const [items, approvals, policies] = await Promise.all([getJson<any>("/api/autonomy/inbox?limit=100"), getJson<any>("/api/autonomy/approvals?status=pending&limit=100"), getJson<any>("/api/autonomy/policies")]);
    return { items: items.items || [], approvals: approvals.approvals || [], policies: policies.policies || [] };
  }, refetchInterval: 5000 });
  const refresh = () => client.invalidateQueries({ queryKey: ["proactive-inbox"] });
  const feedback = useMutation({ mutationFn: ({ id, value }: { id: string; value: string }) => sendJson(`/api/autonomy/inbox/${id}/feedback`, "POST", { feedback: value }), onSuccess: refresh });
  const approval = useMutation({ mutationFn: ({ id, approved }: { id: string; approved: boolean }) => sendJson(`/api/autonomy/approvals/${id}/decision`, "POST", { approved }), onSuccess: refresh });
  const policy = useMutation({ mutationFn: ({ capability, decision }: { capability: string; decision: string }) => sendJson(`/api/autonomy/policies/${encodeURIComponent(capability)}`, "PUT", { decision }), onSuccess: refresh });
  const exclusions = useMutation({ mutationFn: () => sendJson("/api/privacy/capture/exclusions", "PUT", { apps: apps.split(",").map((v) => v.trim()).filter(Boolean), domains: domains.split(",").map((v) => v.trim()).filter(Boolean) }), onSuccess: () => client.invalidateQueries({ queryKey: ["privacy-status"] }) });
  const preset = useMutation({ mutationFn: (value: string) => sendJson("/api/runtime/resource-policy", "PUT", { preset: value }), onSuccess: () => client.invalidateQueries({ queryKey: ["resource-status"] }) });
  const items = inbox.data?.items || [];
  const snapshot = resources?.snapshot || {};
  const freeRam = Number(snapshot.available_ram_mb || 0) / 1024;
  const freeVram = snapshot.free_vram_mb == null ? null : Number(snapshot.free_vram_mb) / 1024;
  return <><PageHeader eyebrow="Judgment-driven assistance" title="Proactive Inbox" description="Review timely opportunities, approve bounded actions, and tune the runtime’s privacy and resource guardrails." actions={<Badge tone={items.length ? "warn" : "neutral"}>{items.length} opportunities</Badge>} />
    {inbox.isLoading && <LoadingState />}{inbox.isError && <ErrorState error={inbox.error} />}
    <div className="two-column wide-left">
      <section className="space-y-3">{!items.length && !inbox.isLoading && <EmptyState title="Inbox is clear" description="New proactive opportunities will appear when Ambient AI finds something timely and useful." />}{items.map((item: any) => <article className="record-card" key={item.inbox_id}><div className="record-top"><div className="flex gap-2"><Badge>{item.status}</Badge><Badge>Confidence {Number(item.confidence || 0).toFixed(2)}</Badge></div><time>{formatDate(item.updated_at)}</time></div><h2>{item.title}</h2><p>{item.summary}</p><div className="meta-grid"><div><strong>Why now</strong><span>{item.why_now}</span></div></div><JsonDetails label="Evidence and sources" value={item.sources_json} /><JsonDetails label="Personalization used" value={item.personalization_json} /><JsonDetails label="Actions and verification" value={item.actions_json} /><JsonDetails label="Detailed result" value={item.detailed_report} /><div className="mt-4 flex flex-wrap gap-2"><Button variant="secondary" onClick={() => feedback.mutate({ id: item.inbox_id, value: "useful" })}><ThumbsUp size={15} />Useful</Button><Button variant="secondary" onClick={() => feedback.mutate({ id: item.inbox_id, value: "not_useful" })}><ThumbsDown size={15} />Not useful</Button><Button variant="ghost" onClick={() => feedback.mutate({ id: item.inbox_id, value: "wrong_inference" })}>Wrong inference</Button><Button variant="ghost" onClick={() => feedback.mutate({ id: item.inbox_id, value: "too_intrusive" })}>Too intrusive</Button>{item.feedback && <Badge tone="good">{item.feedback}</Badge>}</div></article>)}</section>
      <aside className="space-y-4">
        <section className="panel p-4"><div className="section-label"><Lock size={17} />Pending approvals</div>{!inbox.data?.approvals.length && <p className="text-sm text-muted">No actions need approval.</p>}{inbox.data?.approvals.map((item: any) => <div className="sub-card" key={item.approval_id}><Badge>{item.capability}</Badge><p className="my-3 text-sm">This bounded action needs approval before it can run.</p><pre>{typeof item.constraints_json === "string" ? item.constraints_json : JSON.stringify(item.constraints_json, null, 2)}</pre><div className="mt-3 flex gap-2"><Button variant="primary" onClick={() => approval.mutate({ id: item.approval_id, approved: true })}><Check size={15} />Approve once</Button><Button variant="danger" onClick={() => approval.mutate({ id: item.approval_id, approved: false })}><X size={15} />Deny</Button></div></div>)}</section>
        <section className="panel p-4"><div className="section-label"><ShieldCheck size={17} />Capability policies</div><div className="space-y-3">{inbox.data?.policies.map((item: any) => <label className="flex items-center justify-between gap-3 text-sm" key={item.capability}><span className="font-medium">{item.capability}</span><select value={item.decision} onChange={(event) => policy.mutate({ capability: item.capability, decision: event.target.value })}><option value="deny">deny</option><option value="ask">ask</option><option value="auto_reversible">auto reversible</option><option value="trusted_bounded">trusted bounded</option></select></label>)}</div></section>
        <section className="panel p-4"><div className="section-label"><Save size={17} />Capture exclusions</div><div className="form-stack"><label>Applications<input value={apps} onChange={(event) => setApps(event.target.value)} placeholder="1password, signal" /></label><label>Domains<input value={domains} onChange={(event) => setDomains(event.target.value)} placeholder="bank.example, health.example" /></label><Button variant="secondary" onClick={() => exclusions.mutate()} disabled={exclusions.isPending}>Save exclusions</Button><p className="text-xs text-muted">{privacy?.storage_pressure ? "Storage pressure detected. Plain captures will not be auto-deleted." : `Plain captures: ${Math.round(Number(privacy?.capture_size_bytes || 0) / 1048576)} MB · ${privacy?.capture_root || "capture folder"}`}</p></div></section>
        <section className="panel p-4"><div className="section-label"><Gauge size={17} />Resource policy</div><div className="form-stack"><label>Inference preset<select value={resources?.preset || "balanced"} onChange={(event) => preset.mutate(event.target.value)}><option value="capture_only">Capture only</option><option value="balanced">Balanced</option><option value="aggressive">Aggressive</option></select></label><p className="text-xs leading-5 text-muted">{freeRam.toFixed(1)} GB RAM free · {freeVram == null ? "GPU telemetry unavailable" : `${freeVram.toFixed(1)} GB VRAM free`} · model: {resources?.residency?.loaded_model || "on demand"}</p><p className="text-xs text-muted">{Number(resources?.event_counts?.resource_deferred || 0)} resource-deferred · {Number(resources?.event_counts?.pending || 0)} pending events</p></div></section>
      </aside>
    </div>
  </>;
}
